---
title: "Visualization of Research Q"
author: "Yael Yossefy"
date: "2024-11-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Does the relationship between EtCO2 and AMC behave differently in the presence
of relevant medical history? 

```{r}
library(readxl)
data <- read_excel("cardiac_arrests.xlsx")
data[data==9999] <- NA
head(data)
data <- na.omit(data)
```

```{r}
library(ggplot2)
```

```{r}
ggplot(data, aes(x = as.factor(amc), y = etco2, fill = as.factor(hist1))) +
  geom_boxplot() +
  labs(x = "AMC", y = "etco2", fill = "History of coronary artery disease") +
  scale_fill_manual(
    values = c("lightblue", "salmon"), 
    labels = c("No", "Yes")  # Change legend labels from 0/1 to "No"/"Yes"
  ) +
  theme_minimal()
```

```{r}
ggplot(data, aes(x = as.factor(amc), y = etco2, fill = as.factor(hist2))) +
  geom_boxplot() +
  labs(x = "AMC", y = "etco2", fill = "History of congestive heart failure") +
  scale_fill_manual(
    values = c("lightblue", "salmon"), 
    labels = c("No", "Yes")  # Change legend labels from 0/1 to "No"/"Yes"
  ) +
  theme_minimal()
```

```{r}
ggplot(data, aes(x = as.factor(amc), y = etco2, fill = as.factor(hist3))) +
  geom_boxplot() +
  labs(x = "AMC", y = "etco2", fill = "History of chronic kidney disease") +
  scale_fill_manual(
    values = c("lightblue", "salmon"), 
    labels = c("No", "Yes")  # Change legend labels from 0/1 to "No"/"Yes"
  ) +
  theme_minimal()
```

```{r}
ggplot(data, aes(x = as.factor(amc), y = etco2, fill = as.factor(hist4))) +
  geom_boxplot() +
  labs(x = "AMC", y = "etco2", fill = "History of diabetes mellitus") +
  scale_fill_manual(
    values = c("lightblue", "salmon"), 
    labels = c("No", "Yes")  # Change legend labels from 0/1 to "No"/"Yes"
  ) +
  theme_minimal()
```



```{r}
ggplot(data, aes(x = as.factor(amc), y = etco2, fill = as.factor(hist5))) +
  geom_boxplot() +
  labs(x = "AMC", y = "etco2", fill = "History of Myocardial Infarction") +
  scale_fill_manual(
    values = c("lightblue", "salmon"),  # Optional: Customize colors
    labels = c("No", "Yes")  # Change legend labels from 0/1 to "No"/"Yes"
  ) +
  theme_minimal()

```


```{r}
ggplot(mtcars, aes(x = amc, y = etco2)) +
  geom_violin() +
  labs(x = "Number of Cylinders", y = "Miles per Gallon") +
  theme_minimal()

```
